### ISSUE TITLE
New REDIRECT_HOSTS: email.ifttt.com

### ISSUE THREAD

**Issue by timendum** [GermainZ/CrappaLinks#18]
Hi,
a new redirect host: email.ifttt.com

Sample url: http://email.ifttt.com/wf/click?upn=6tNAOFwxcF8KzWlMrDEXkIEDiqSckzA7sBu1-2B1B9l5F3lujUt2A-2BeGQxVQ0NoVkmw2F5EK31GGIBh5aeshyFcA-3D-3D_w5YHRgGU7wm4Xmq3w6X54bTSwjHM03C-2FPs6A7-2FTRdVUau26Mmkpr4H6iPgyg8gVRrUw5g7tiWBSDX4jlJ2eyftuihbk0M8S-2FnbVlwRzGisWRkrhX-2BkSGE0gMHaymtY2nJwLgMpM0HeOxNRrfaL6qRJi5ZwuLpoVZ3OmqYishuZCnnWshXeznVQjd-2FYZbW5kTW60wh3xQLogvXyORHzlqRLcn1ZrdU2GlmfyPnT9Tc8SP1HOplBhovNP9MJsHhwCGc1xMTnB2AcfjjA9dUr7i5g-3D-3D
Resolve to: https://ifttt.com/myrecipes/personal/8429017

Thanks

**Comment by GermainZ** [comment]
This will be in the next version, thanks!
