### ISSUE TITLE
Minimum updates will make this one functional again

### ISSUE THREAD

**Issue by ghost** [GermainZ/CrappaLinks#27]
at the ResolveUrl:  
change <code>"http://api.longurl.org/v2/expand?format=json&title=1&url="</code>  
to <code>http://unshorten.me/json/</code>  
(possibly avoid URL encoding, and removing https prefix too before).  
and:  
change <code>"long-url"</code>  
to <code>"resolved_url"</code>  

you might be able to use HTTP as is (instead of connection being upgraded to HTTPS automatically) if you don't want to use HTTPS, with <code>android:usesCleartextTraffic="true"</code> property, added to the <code>&lt;application </code> before the end <code>&gt;</code>.

see https://unshorten.me/api 

plus, the external API supports quite a lot of additional domains.  
the exact amount is unclear, but I've collected a list of common short-links domains,  
and simply try to see if the result has anything useful in it.

<details><summary>here is my list</summary>
<pre>
0rz.tw
1link.in
1url.com
2.gp
2big.at
2tu.us
3.ly
4ms.me
4sq.com
4url.cc
6url.com
7.ly
307.to
›.ws
✩.ws
✿.ws
❥.ws
➔.ws
➞.ws
➡.ws
➨.ws
➯.ws
➹.ws
➽.ws
a.gg
a.nf
aa.cx
abcurl.net
ad.vu
adf.ly
adjix.com
affiliation.appgratuites-network.com
afx.cc
aka.ms
all.fuseurl.com
alturl.com
amzn.to
ar.gy
arst.ch
atu.ca
azc.cc
b2l.me
b23.ru
bacn.me
bcool.bz
binged.it
bit.ly
bitly.com
bizj.us
bloat.me
bravo.ly
bsa.ly
budurl.com
buff.ly
canurl.com
chilp.it
chip.biz
chzb.gr
cl.lk
cl.ly
clck.ru
cli.gs
cliccami.info
clickthru.ca
clipurl.us
clop.in
cnn.it
cnnmon.ie
conta.cc
cort.as
cos.as
cot.ag
crks.me
ctvr.us
cutt.us
dai.ly
db.tt
decenturl.com
dfl8.me
digbig.com
digg.com
disq.us
dld.bz
dlvr.it
do.my
doiop.com
dopen.us
dopice.sk
dustn.ws
dwarfurl.com
easyuri.com
easyurl.net
ed.cl
eepurl.com
engt.co
eweri.com
fa.by
fav.me
fb.me
fbshare.me
feedproxy.google.com
ff.im
fff.to
fire.to
firsturl.de
firsturl.net
flic.kr
flip.it
flq.us
fly2.ws
fon.gs
freak.to
fuseurl.com
fuzzy.to
fwd4.me
fwib.net
g.page
g.ro.lt
gizmo.do
gl.am
glm.io
go.9nl.com
go.ign.com
go.usa.gov
goo.gl
goshrink.com
gurl.es
hex.io
hiderefer.com
hmm.ph
href.in
hsblinks.com
ht.ly
htn.to
htxt.it
huff.to
hukd.mydealz.de
hulu.com
hurl.me
hurl.ws
icanhaz.com
idek.net
ift.tt
ilix.in
is.gd
its.my
ix.lt
j.mp
jijr.com
kck.st
kcy.me
kl.am
klck.me
korta.nu
krunchd.com
l9k.net
lat.ms
liip.to
liltext.com
lin.cr
linkbee.com
linkbun.ch
liurl.cn
ln-s.net
ln-s.ru
lnk.gd
lnk.ms
lnkd.in
lnkurl.com
loopt.us
lost.in
lru.jp
lt.tl
lurl.no
macte.ch
mash.to
mbsy.co
mdk.to
memurl.com
menea.me
merky.de
mhlthm.ag
migre.me
miniurl.com
minurl.fr
mir.cr
mke.me
moby.to
moourl.com
mrte.ch
mun.do
myloc.me
myurl.in
n.pr
nanourl.se
nazr.in
nbc.co
nblo.gs
nerdi.st
nn.nf
not.my
notlong.com
nsfw.in
nutshellurl.com
nxy.in
nyti.ms
o-x.fr
oc1.us
officeurl.com
ohmyyy.gt
om.ly
omf.gd
omoikane.net
on.cnn.com
on.mktw.net
onforb.es
orz.se
ow.ly
peaurl.com
phon.es
ping.fm
piurl.com
pli.gs
plurl.me
pnt.me
po.st
politi.co
poprl.com
post.ly
pp.gg
profile.to
ptiturl.com
pub.vitrue.com
pulse.me
qlnk.net
qrli.to
qte.me
qu.tc
qy.fi
r.im
rb6.me
rde.me
read.bi
readthis.ca
reallytinyurl.com
redd.it
redes.li
redir.ec
redirects.ca
redirx.com
retwt.me
reut.rs
ri.ms
rickroll.it
riz.gd
rt.nu
ru.ly
rubyurl.com
rurl.org
rww.tw
s4c.in
s7y.us
safe.mn
sameurl.com
sdut.us
shar.es
share.epidemicsound.com
sharepointurl.com
shink.de
shorl.com
short.ie
short.to
shortlinks.co.uk
shorturl.com
shout.to
show.my
shrinkify.com
shrinkr.com
shrt.fr
shrt.st
shrten.com
shrunkin.com
simurl.com
slate.me
smallr.com
smsh.me
smurl.name
sn.im
sn.vc
snipr.com
snipurl.com
sns.mx
snurl.com
sp2.ro
spedr.com
spon.de
spr.ly
srnk.net
srs.li
starturl.com
su.pr
surl.co.uk
surl.hu
surl.link
surl.ms
t.cn
t.co
t.lh.com
ta.gd
tbd.ly
tcrn.ch
tgr.me
tgr.ph
tighturl.com
tiniuri.com
tiny.cc
tiny.ly
tiny.pl
tinylink.in
tinysong.com
tinyuri.ca
tinyurl.com
tk.
tl.gd
tmblr.co
tmi.me
tnij.org
tnw.to
tny.com
to.
to.ly
togoto.us
totc.us
toysr.us
tpm.ly
tr.im
tra.kz
trg.li
trib.al
trim.li
trunc.it
twhub.com
twirl.at
twitclicks.com
twitterurl.net
twitterurl.org
twiturl.de
twurl.cc
twurl.nl
u76.org
u.mavrev.com
u.nu
ub0.cc
ulu.lu
untp.i
updating.me
ur1.ca
url4.eu
url360.me
url.az
url.cn
url.co.uk
url.ie
urlborg.com
urlbrief.com
urlcover.com
urlcut.com
urlenco.de
urli.nl
urls.im
urlshorteningservicefortwitter.com
urlx.ie
urlzen.com
usat.ly
use.my
v0v.in
v.ht
vaugette.com
vb.ly
ve42.co
vgn.am
vl.am
vm.lc
vrge.co
w34.us
w55.de
wapo.st
wapurl.co.uk
wh.gov
wipi.es
wp.me
www.qrli.to
x.vu
xr.com
xrl.in
xrl.us
xurl.es
xurl.jp
y2u.be
y.ahoo.it
yatuc.com
ye.pe
yep.it
yfrog.com
yhoo.it
yiyd.com
youtu.be
yuarel.com
z0p.de
zi.ma
zi.mu
zipmyurl.com
zud.me
zurl.ws
zz.gd
zzang.kr
</pre>
</details>

edit: I've meant, in my web-extension (combine extraction-logic (offline), with external resolving using above API): https://github.com/eladkarako/chrome_extensions/tree/store/Remove-Redirects-Plus/README.md

**Comment by victay44** [comment]
I found a link to your repo on xda but the link is dead. Is it alright to reupload it? TIA.
[crappalinks](https://github.com/eladkarako/xposed_crappalinks__mod_api__unshortenme/blob/modified_source/CrappaLinks%203.0.1_301__mod_api.apk.zip)
