### ISSUE TITLE
more domains, domain submission form?

### ISSUE THREAD

**Issue by Efreak** [GermainZ/CrappaLinks#8]
ht.ly is handled by ow.ly, and George Takei's ohmyyy.gt is handled by po.st.

There are several other services that allow you to set up your own short url service. Perhaps you could set up a Google docs form or something so we can tell you about them without submitting issues or posting on xda.

**Comment by josteink** [comment]
[donotlink.com](http://donotlink.com) is also extremely annoying and showing more and more up in my facebook feed. It should IMO get added to the list.

From what I can see it's the redirecting kind. Would adding it to [RedirectHelper](https://github.com/GermainZ/CrappaLinks/blob/master/src/com/germainz/crappalinks/RedirectHelper.java) be sufficient?

**Comment by jawz101** [comment]
How about these?  I've aggregated them from a few longurl sites and whitepapers :)  Do I win?
http://pastebin.com/jtbizY3h

**Comment by GermainZ** [comment]
Apologies for the late reply everyone.

@josteink: yes, but it seems it's gone down.
@jawz101: I'm reluctant to add a gigantic list as I'd like to keep the overhead to a minimum. Perhaps in the future with some code changes to ensure optimal lookup times.

**Comment by Efreak** [comment]
I've actually been using [unshorten](https://play.google.com/store/apps/details?id=com.teaandtoys.unshorten&hl=en) lately, as I've been trying to cut down on the number of xposed modules I'm using (tracking down bugs and incompatibilities has gotten insanely hard) and no longer have as much need for it to begin with (I seem to be coming across fewer shorturls outside of the browser now). You may want to consider moving to a method like this where instead of using xposed you simply register the app as the handler for such urls, resolve them, then open them natively. The masking issue would then be the only thing left, and I rarely see that in apps--more often the link has text on it than the shorturl address. This could be dealt with by a popup on links that tells the destination url before opening it.

This is quite a decent app, but I'm just finding it too hard to track down glitches in xposed lately (I've had 6 different crashing bugs and a bootlooping issue in the past 2 months, and tracking them down through 10+ xposed modules is more work than it's worth)

**Comment by GermainZ** [comment]
There are already apps that do it the normal way, so I don't see the point 
of that. This module's goal is transparency -- it works without showing up 
in the resolver list, which would get annoying if you have multiple 
browsers or tend to install new apps.

**Comment by Efreak** [comment]
True enough. I hadn't thought about having _many_ browsers. FWIW, I have ~7 installed (gimme my multi window/session/profile browser back :frowning:) and refuse to set one as default, but I _do_ set unshorten as default wherever possible to solve the issue of it coming up in the list and then having to get the list again.

Unshorten also doesn't help _at all_ with apps that open links in-app using the new chrome activity/feature/whatever, but I have that disabled anyways.
